[package]
name = "scriptant"
version = "0.2.1"
edition = "2021"
authors = ["Mozk Taberenai <mozk@me.com>"]
description = "Rust scripting assistant"

[dependencies]
anyhow = "1.0"
once_cell = "1.15.0"
smallvec = "1.10.0"

[[example]]
name = "cmd"
[[example]]
name = "env"
[[example]]
name = "fs"
