[package]
name = "scriptant"
version = "0.5.0"
edition = "2021"
authors = ["Mozk Taberenai <mozk@me.com>"]
license = "MIT"
description = "Rust scripting assistant"
repository = "https://github.com/MozkTaberenai/scriptant"
homepage = "https://github.com/MozkTaberenai/scriptant"
categories = ["command-line-interface"]

[dependencies]
once_cell = "1.17.1"
smallvec = "1.10.0"

[[example]]
name = "cmd"
[[example]]
name = "env"
[[example]]
name = "fs"
