[package]
name = "scriptant"
version = "0.10.0"
edition = "2021"
authors = ["Mozk Taberenai <mozk@me.com>"]
license = "MIT"
description = "Rust scripting assistant"
repository = "https://github.com/MozkTaberenai/scriptant"
homepage = "https://github.com/MozkTaberenai/scriptant"
categories = ["command-line-interface"]

[[example]]
name = "cmd"
[[example]]
name = "env"
[[example]]
name = "fs"
[[example]]
name = "ansi"
[[example]]
name = "ansi-true-color"
